services:
  postgres:
    image: postgres:15
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount your setup script to the initdb directory
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql:ro

volumes:
  postgres_data:
