version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - task run

  build:
    desc: Build the Go application binary
    cmds:
      - go build -o ./bin/api ./cmd/api

  run:
    desc: Run the application using Docker Compose and Air for hot reloading
    cmds:
      - task build
      - docker-compose up -d
      - air

  stop:
    desc: Stop the Docker Compose environment
    cmds:
      - docker-compose down

  tests:
    desc: Run all Go tests
    cmds:
      - go test ./...

  db:push:
    desc: Push the migrations to the database using Drizzle
    cmds:
      - cd ./db/drizzle && pnpm run push

  db:introspect:
    desc: Introspect the database schema using Drizzle
    cmds:
      - cd ./db/drizzle && pnpm run introspect

  db:studio:
    desc: Open the Drizzle Studio
    cmds:
      - cd ./db/drizzle && pnpm run studio

  db:gen_migrate:
    desc: Generate migrations
    cmds:
      - cd ./db/drizzle && pnpm run generate

  db:gen_query:
    desc: Generate SQLC code from queries
    cmds:
      - rm -rf ./internal/repository/postgres && sqlc generate
